"use server";

import { auth } from "@clerk/nextjs/server";
import { revalidatePath } from "next/cache";
import { createServerSupabaseClient } from "@/lib/supabase-server";
import { extractFactBase, ExtractFactBaseOptions, ExtractFactBaseResult } from "@/lib/cv/extract";
import {
  tailorCV as tailorCVImpl,
  refineTailoredCV as refineTailoredCVImpl,
  TailorInput,
  RefineInput,
  TailorResult,
} from "@/lib/cv/tailor";
import type { TailoredCV } from "@/lib/cv/tailored-cv";

export async function getFactBase(
  options: ExtractFactBaseOptions = {}
): Promise<ExtractFactBaseResult> {
  return extractFactBase(options);
}

export async function tailorCV(input: TailorInput): Promise<TailorResult> {
  return tailorCVImpl(input);
}

export async function refineTailoredCV(input: RefineInput): Promise<TailorResult> {
  return refineTailoredCVImpl(input);
}

// ── Saved tailored CVs (linked to applications) ──────────────────────────────

export interface SavedTailoredCV {
  id: string;
  application_id: string | null;
  company: string | null;
  role: string | null;
  jd_text: string | null;
  tailored_data: TailoredCV | null;   // null for manually-pasted CVs
  content: string | null;             // plain text fallback (always populated)
  created_at: string;
}

export async function saveTailoredCV(input: {
  tailoredCV: TailoredCV;
  applicationId?: string;
  companyName?: string;
  roleName?: string;
  jdText?: string;
}): Promise<{ id?: string; error?: string }> {
  try {
    const { userId } = await auth();
    if (!userId) return { error: "Not signed in" };

    const supabase = await createServerSupabaseClient();
    const plain = serialiseTailoredCVPlain(input.tailoredCV);

    const { data, error } = await supabase
      .from("cv_versions")
      .insert({
        user_id: userId,
        application_id: input.applicationId ?? null,
        company: input.companyName ?? null,
        role: input.roleName ?? null,
        jd_text: input.jdText ?? null,
        tailored_data: input.tailoredCV,
        content: plain,
      })
      .select("id")
      .single();

    if (error) {
      console.error("[saveTailoredCV] supabase error:", error);
      return { error: error.message };
    }
    revalidatePath("/tracker");
    revalidatePath("/cv");
    return { id: data?.id };
  } catch (e) {
    console.error("[saveTailoredCV] unexpected:", e);
    return { error: e instanceof Error ? e.message : "Failed to save tailored CV." };
  }
}

export async function getSavedTailoredCVs(
  applicationId?: string
): Promise<SavedTailoredCV[]> {
  const { userId } = await auth();
  if (!userId) return [];

  const supabase = await createServerSupabaseClient();
  const query = supabase
    .from("cv_versions")
    .select("id, application_id, company, role, jd_text, tailored_data, content, created_at")
    .eq("user_id", userId)
    .order("created_at", { ascending: false });

  if (applicationId) {
    query.eq("application_id", applicationId);
  }

  const { data, error } = await query;
  if (error) {
    console.error("[getSavedTailoredCVs] error:", error);
    return [];
  }
  return (data ?? []) as SavedTailoredCV[];
}

// Save a CV that was used externally (not generated by the SaaS) — paste-and-attach.
export async function saveManualCV(
  applicationId: string,
  content: string
): Promise<{ id?: string; error?: string }> {
  try {
    const { userId } = await auth();
    if (!userId) return { error: "Not signed in" };
    if (!content || !content.trim()) return { error: "CV content is empty" };

    const supabase = await createServerSupabaseClient();
    const { data, error } = await supabase
      .from("cv_versions")
      .insert({
        user_id: userId,
        application_id: applicationId,
        content: content.trim(),
        tailored_data: null,
      })
      .select("id")
      .single();

    if (error) {
      console.error("[saveManualCV] supabase error:", error);
      return { error: error.message };
    }
    revalidatePath("/tracker");
    return { id: data?.id };
  } catch (e) {
    console.error("[saveManualCV] unexpected:", e);
    return { error: e instanceof Error ? e.message : "Failed to save CV." };
  }
}

function serialiseTailoredCVPlain(cv: TailoredCV): string {
  const lines: string[] = [];
  lines.push(cv.contact.name);
  lines.push(
    [cv.contact.location, cv.contact.email, cv.contact.phone, cv.contact.linkedin]
      .filter(Boolean)
      .join("  ·  ")
  );
  if (cv.summary) {
    lines.push("", "PROFILE", cv.summary);
  }
  if (cv.skills.length > 0) {
    lines.push("", "KEY SKILLS");
    for (const g of cv.skills) lines.push(`${g.category}: ${g.items.join(", ")}`);
  }
  if (cv.roles.length > 0) {
    lines.push("", "EXPERIENCE");
    for (const r of cv.roles) {
      const dates = r.isCurrent ? `${r.startDate} – Present` : `${r.startDate} – ${r.endDate ?? ""}`;
      lines.push(`${r.title} — ${r.company}${r.location ? `, ${r.location}` : ""} (${dates.trim()})`);
      for (const b of r.bullets) lines.push(`• ${b}`);
    }
  }
  if (cv.education.length > 0) {
    lines.push("", "EDUCATION");
    for (const e of cv.education) {
      const years = [e.startYear, e.endYear].filter(Boolean).join(" – ");
      lines.push(`${e.qualification} — ${e.institution}${e.classification ? ` (${e.classification})` : ""}${years ? ` [${years}]` : ""}`);
      if (e.details) lines.push(`  ${e.details}`);
    }
  }
  if (cv.certifications.length > 0) {
    lines.push("", "CERTIFICATIONS");
    for (const c of cv.certifications) {
      const meta = [c.issuer, c.year].filter(Boolean).join(", ");
      lines.push(`• ${c.content}${meta ? ` (${meta})` : ""}`);
    }
  }
  if (cv.languages.length > 0) {
    lines.push("", "LANGUAGES", cv.languages.map((l) => `${l.language} (${l.proficiency})`).join(", "));
  }
  if (cv.interests.length > 0) {
    lines.push("", "INTERESTS", cv.interests.join(", "));
  }
  return lines.join("\n");
}
